config/routes.rb
require_relative "../lib/nxt_apps_constraint"

Rails.application.routes.draw do
  #get 'home_page/index'
  use_doorkeeper do
    controllers :applications => 'nxt_apps'
  end

  # Add a route for OAuth logout
  get 'oauth/logout', to: 'sessions#destroy', as: 'oauth_logout'

  resources :users

  # Homepage Routes
  root to: 'home_page#index'

  # Session and user routes
  get '/' => 'users#index'
  post 'users' => 'users#create'
  post 'sessions' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  # App routes
  scope 'app/:app', constraints: NxtAppsConstraint.new do
    resources :posts
    resources :email_templates
    get '/' => 'crms#index'
    get 'admin', to: 'admin#userpage', as: 'admin'
    get 'admin/index', to: 'admin#index', as: 'adminview'
    get 'analytics', to: 'analytics#index', as: 'analytics'
    get 'posts/bytype/:user_type', to: 'posts#bytype', as: 'bytype'
    post 'posts/sendto', to: 'posts#sendto', as: 'sendto'
    get 'email_templates/:title/fill_in' => 'email_templates#fill_in', as: 'fill_in'
  end

  get 'crmusers' => 'users#usermanage'
  get 'dashboard' => 'dashboard#index'
  post 'update_permission', to: 'users#update_permission'
  get 'home' => 'user_dashboard#index'

  # Password Stuff
  get "password" => "passwords#edit"
  patch "password" => "passwords#update"

  # Password Reset
  get "password/reset" => "password_resets#new"
  post "password/reset" => "password_resets#create"
  get "password/reset/edit" => "password_resets#edit"
  patch "password/reset/edit" => "password_resets#update"

  #Admin Mailer

  # get "admin/request" => "admin_requests#new"
  # post "admin/request/tokenUser" => "admin_requests#tokenUser"
  # get "admin/request/tokenUser" => "admin_requests#tokenUser"
  # patch "admin/request/tokenUser" => "admin_requests#approve"

  scope "admin/request" do
    get   "/" => "admin_requests#new",as: :adrq_new
    post  "tokenUser" => "admin_requests#tokenUser", as: :adrq_post
    get   "tokenUser" => "admin_requests#tokenUser", as: :adrq_get
    patch "tokenUser" => "admin_requests#approve" , as: :adrq_approve
  end

  # API routes for other OAuth apps
  namespace :api do
    get 'user' => 'user#show'
  end
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates_presence_of :recipient
    validates_presence_of :title
    validates_presence_of :content
    mount_uploader :image, ImageUploader

    alias_attribute :application_id, :oauth_applications_id
    
    def to_s
      title
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'httparty'
  before_action :set_post_app
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :get_users, only: [:create, :new, :bytype, :sendto]
  
  def index
    @posts = Post.where(application_id: @nxtapp.id)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Posts: #{@posts.count}", template: "posts/index.html.erb"
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Post id: #{@post.id}", template: "posts/show.html.erb"
      end
    end
  end

  def new
    session.delete(:post_recipient)
    session.delete(:post_title)
    session.delete(:post_content)
    @post = params[:post] ? Post.new(post_params) : Post.new
    session[:post_recipient] = @post.recipient if @post.recipient.present?
    session[:post_title] = @post.title if @post.title.present?
    session[:post_content] = @post.content if @post.content.present?
    @user_types
  end

  def edit
  end

  def create
    post_params_new = post_params.dup
    post_params_new[:application_id] = @nxtapp.id
    @post = Post.new(post_params_new)
    if @post.save
      EventMailer.event_created.deliver_later
      redirect_to post_url(id: @post.id), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    post_params_new = post_params.dup
    post_params_new[:application_id] = @nxtapp.id
    if @post.update(post_params_new)
      redirect_to post_url(id: @post.id), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  def bytype
    @user_type = params[:user_type]
    @type_user = @users_by_type[@user_type]
  end

  def sendto
    selected_user_ids = params[:selected_user_ids]
    @type_user = @users.select{ |user| selected_user_ids.include?(user['id'].to_s) }
    recipient_string = @type_user.map{ |user| "#{user['name']} <#{user['email']}>"}.join('; ')
    @post = Post.new({recipient: recipient_string})
    @post.title = session[:post_title] if session[:post_title].present?
    @post.content = session[:post_content] if session[:post_content].present?
    redirect_to new_post_path(post: @post.attributes)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:recipient, :title, :content, :image)
    end

    def set_post_app
      app = params[:app]
      @nxtapp = NxtApps.find_by(name: app)
    end

    def get_users
      users_url = URI::join(@nxtapp.api_url, 'users')
      res = HTTParty.get(users_url)
      if res.success?
        @users = JSON.parse(res.body)
        @users_by_type = {}
        @users.each do |user|
          user_type = user['user_type']
          if @users_by_type.has_key?(user_type)
            @users_by_type[user_type] << user
          else
            @users_by_type[user_type] = [user]
          end
        end
        @user_types = @users_by_type.keys
      else
        # Return with an error
        flash[:error] = 'API URL or @app not set for this application'
        redirect_to '/'
      end
    end
end

app/views/posts/_form.html.erb
<div class="row">
<div class="col-md-5">
<%= form_with(model: post, url: post.new_record? ? posts_path(app: @nxtapp.name) : post_path(app: @nxtapp.name, id: post.id), method: post.new_record? ? :post : :put) do |form| %>
  <%# this form is used for both new post and edit post. The line above ensures it works for both after adding foreign key. %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-3 field">
    <%= form.label :recipient, class: 'form-label' %>
    <%= form.text_field :recipient, required: true, class: 'form-control' %>
  </div>

  <div class="mb-3 field">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, required: true, class: 'form-control' %>
  </div>

  <div class="mb-3 field">
    <%= form.label :content, class: 'form-label' %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="mb-3 field">
    <%= form.label :image, class: 'form-label' %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Send Post", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>
</div>

app/views/posts/bytype.html.erb
<h1 class="pg-title"><u>User Type: <%= @user_type %></u></h1>
<div class="tbl-wrapper">
  <%= form_tag sendto_path, method: :post do %>   
  <table class="crm-tbl">
    <br/>
    <thead>
      <tr>
        <th>User ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Membership Type</th>
      </tr>
    </thead>
        <tbody> 
            <% @type_user.each do |user| %>
                <tr>
                    <td><%= user['id'] %></td>
                    <td><%= user['name'] %></td>
                    <td><%= user['email'] %></td>
                    <td><%= user['user_type'] %></td>
                    <td>
                      <%= check_box_tag 'selected_user_ids[]', user['id'] %>
                      <%= label_tag "Selected" %>
                    </td>
                </tr>
            <% end %>
        </tbody>    
    </table>
    <br/>
    <%= submit_tag 'Select Recipients' %>
  <% end %>
  <br/>
  <%= link_to 'Back', new_post_path %>
</div>

app/views/posts/edit.html.erb
<h1 class="pg-title"><u>Editing Post</u></h1>
<div class="tbl-wrapper">
    <%= render 'form', post: @post %>

    <%= link_to 'Show', post_path %> |
    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<nav style="--bs-breadcrumb-divider: '>';" class="border-bottom mb-4" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
    <li class="breadcrumb-item"><a href="#"><%= @app %></a></li>
    <li class="breadcrumb-item active">Email Notifications</li>
  </ol>
</nav>
<div class="row align-items-center justify-content-between g-3 mb-5 col-12 col-md-auto">
  <h1 class="mb-0 pg-title"><%= @app %> Email Notifications</h1>
</div>
<div class="tbl-wrapper">
  <table class="crm-tbl">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Content</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>
          <td><%= post.title %></td>
          <td><%= simple_format(post.content) %></td>
          <td><%= link_to 'PDF', post_path(id: post.id, format: :pdf) %></td>
          <td><%= link_to 'Show', post_path(id: post.id) %></td>
          <td><%= link_to 'Edit', edit_post_path(id: post.id) %></td>
          <td><%= link_to 'Destroy', post_path(id: post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br/>
<div class="tbl-wrapper">
  <h3>Import Reports</h3>
  <%= link_to 'New Report', new_post_path %>
  <br/>
  <%= link_to 'Templates list', email_templates_path %>
  <br/>
  <%= link_to "Reports PDF", posts_path(format: :pdf) %>
</div>

app/views/posts/new.html.erb
<nav style="--bs-breadcrumb-divider: '>';" class="border-bottom mb-4" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
    <li class="breadcrumb-item"><a href="#"><%= @app %></a></li>
    <li class="breadcrumb-item"><%= link_to "Email Notifications","/app/#{@app}/posts" %></li>
    <li class="breadcrumb-item active">New Post</li>
  </ol>
</nav>
<div class="row align-items-center justify-content-between g-3 mb-5 col-12 col-md-auto">
  <h1 class="mb-0 pg-title">New Post</h1>
</div>
<div class="tbl-wrapper container-fluid mx-0">
    <%= render 'form', post: @post %>
    <br/>
    <%= "Recipient types: " %>
    <% @user_types.each do |type| %>
      <%= link_to type, bytype_path(user_type: type) %>
      &nbsp;
    <% end %>
    <br/>
    <%= link_to 'Templates list', email_templates_path %>
    <br/>
    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/post.html.erb
PDF generation date:
<%= Time.zone.now %>

<p>
  <strong>Post ID:</strong>
  <%= @post.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format(@post.content) %>
</p>

app/views/posts/show.html.erb
<div class="tbl-wrapper">
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= simple_format(@post.content) %>
  </p>

  <%= image_tag(@post.image.url, alt: 'Attachment') if @post.image? %>

  <%= link_to 'Edit', edit_post_path %> |
  <%= link_to 'Back', posts_path %>
</div>